services:
  db:
    image: mongo:latest
    container_name: axum-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpw
      - MONGO_INITDB_DATABASE=axum-mongo
    ports:
      - 27017:27017
    volumes:
      - axum-mongo-volume:/data/db

volumes:
  axum-mongo-volume:
